events {}

http {
    upstream analytics_backend {
        server analytics:8000;
    }

    upstream filter_backend {
        server filter:8000;
    }

    upstream trend_backend {
        server trend:8000;
    }

    server {
        listen 80;

        location /analytics/ {
            proxy_pass http://analytics_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /filter/ {
            proxy_pass http://filter_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /trend/ {
            proxy_pass http://trend_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
